LTO_ENABLE = yes
VIA_ENABLE = yes
VIAL_ENABLE = yes
MOUSEKEY_ENABLE = yes
#VIALRGB_ENABLE = yes
#WS2812_DRIVER_REQUIRED = yes
EXTRAKEY_ENABLE = yes
TAP_DANCE_ENABLE = no
#RGB_MATRIX_ENABLE = yes
#RGB_MATRIX_DRIVER = ws2812
#KEY_OVERRIDE_ENABLE = yes
#CONSOLE_ENABLE = yes
#COMMAND_ENABLE = no
#EXTRAKEY_ENABLE = no
#SPACE_CADET_ENABLE = no
#GRAVE_ESC_ENABLE = no 
#MAGIC_ENABLE = yes
#MUSIC_ENABLE = no
#EXTRAFLAGS += -flto
#UNICODE_ENABLE = no  # Unicode
#ifeq ($(strip $(CONSOLE_ENABLE)), yes)
 #   TMK_COMMON_DEFS += -DCONSOLE_ENABLE
#else
 #   TMK_COMMON_DEFS += -DNO_PRINT
  #  TMK_COMMON_DEFS += -DNO_DEBUG
#endif
#BACKLIGHT_ENABLE = yes
RGBLIGHT_ENABLE = yes
#AVR_USE_MINIMAL_PRINTF = yes
